# Generated by Django 4.1.3 on 2023-01-02 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.CharField(
                default=uuid.uuid4, max_length=500, primary_key=True, serialize=False
            ),
        ),
    ]
