# Generated by Django 4.1.3 on 2023-01-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_post_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
    ]
